
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiZW1haWwiOiJoZW4uZGFuaWVsNDdAZ21haWwuY29tIiwibmFtZSI6IkRhbmllbCBIZW4iLCJyb2xlIjoiMSIsIm5iZiI6MTc3NDg2Nzc4MywiZXhwIjoxNzc0ODcxMzgzLCJpYXQiOjE3NzQ4Njc3ODMsImlzcyI6ImRvYXItY2hhdCIsImF1ZCI6ImRvYXItY2hhdC11c2VycyJ9.Kz47Pcxd6hI-JGD3iY9oeJYFEtVXrtrq4Vx2NtwTgkw

# Create new user account
POST http://localhost:5207/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "P@ssw0rd!",
  "name": "Test User"
}

###
# Login and get token
POST http://localhost:5207/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "P@ssw0rd!"
}

###
# List all registered users
GET http://localhost:5207/users
Authorization: Bearer {{token}}

###
# Delete user by id
DELETE http://localhost:5207/users/1
Authorization: Bearer {{token}}

###
# Get conversation with user
GET http://localhost:5207/messages/with/2
Authorization: Bearer {{token}}

###
# Send message
POST http://localhost:5207/messages
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "receiverUserId": 5,
  "content": "Hey, how are you?"
}
